/*
 * userExitCodes.h
 *
 *  Created on: 14 мая 2018 г.
 *      Author: bortsov
 */

#ifndef INCLUDE_USEREXITCODES_H_
#define INCLUDE_USEREXITCODES_H_

#ifdef __cplusplus
extern "C" void exit(int) __attribute__((noreturn));
#else
void exit(int) __attribute__((noreturn));
#endif


enum EXIT_CODES {
    EXIT_SYSTEM_NO_MEMORY = 1,
    EXIT_SYSTEM_INVALID_HCLK_SOURCE,
    EXIT_SYSTEM_MAIN_OSCILLATOR_FAIL,
    EXIT_VIM_INVALID_IRQ_NUMBER,
    EXIT_VIM_IRQ_IS_ALREADY_REGISTERED,
    EXIT_HET_INVALID_HR_CLOCKS,
    EXIT_HET_INVALID_PROGRAM_SIZE,
    EXIT_HET_INVALID_PROGRAM_ADDRESS,
    EXIT_HET_NO_SPACE_TO_REGISTER_USER_IRQ,
    EXIT_HET_INVALID_BASE_ADDRESS,
    EXIT_HET_INVALID_RAM_ADDRESS,
    EXIT_ADC_INVALID_CLOCKS,
    EXIT_ADC_INVALID_CAPACITOR_DISCHARGE_CLOCKS,
    EXIT_ADC_INVALID_CHANNEL_ACQUIZION_CLOCKS,
    EXIT_ADC_INVALID_SETUP_BUFFERS,
    EXIT_ADC_IS_ALREADY_CREATED,
    EXIT_ADC_NO_SPACE_TO_REGISTER_USER_IRQ,
    EXIT_ADC_USER_IRQ_HANDLER_IS_ALREADY_REGISTERED,
    EXIT_ADC_USER_IRQ_CHANNEL_IS_ALREADY_REGISTERED,
    EXIT_ADC_INVALID_CHANNEL_TO_REGISTER_USER_IRQ,
    EXIT_SCI_IS_ALREADY_CREATED,
    EXIT_SCI_UNABLE_TO_SET_BAUDRATE,
    EXIT_SCI_BIG_BAUDRATE_ERROR,
    EXIT_SCI_INVALID_USER_HANDLER_TO_RECEIVE,
    EXIT_MONITOR_INVALID_OBJECT_TO_USE,
    EXIT_MONITOR_NO_SPACE_TO_REGISTER_COMMAND,
    EXIT_PHYSV_BOARDVOLTAGE_IS_ALREADY_CREATED,
    EXIT_PHYSV_BOARDVOLTAGE_IS_NOT_CREATED,
    EXIT_PINS_INVALID_SPI_NUMBER,
    EXIT_PINS_INVALID_TESTPIN
};



#endif /* INCLUDE_USEREXITCODES_H_ */
